- name: popping up nginx and openresty containers
  hosts: all

  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
   - {role: docker, become: yes}

  tasks:
    - name: copy Docker Compose file
      copy:
        src: docker-compose.yml
        dest: /tmp

    - name: deploy Docker Compose services
      become: yes
      docker_compose:
        project_src: /tmp
        state: present
    - name: shut down the services
      docker_compose:
        project_src: /home/kali/Documents/Challenge
        state: absent

    - name: Create and start services
      docker_compose:
        project_src: /home/kali/Documents/Challenge
        build: yes
      register: output
    
    - debug:
        var: output